# tests/test_rollout_reinforce.py

import math

import numpy as np
import torch

import config.simulation as SIM_CONFIG

from src.algorithms.reinforce import PolicyNetwork, compute_action_log_probs, sample_action
from src.env import PlanarClawEnv
from src.rollout import rollout_episode, sample_episode


# Test trajectory structure
def test_rollout_episode():
    # Initialise
    env = PlanarClawEnv(gui=False)
    policy = PolicyNetwork()
    gamma = 0.99

    try:
        # Sample trajectory
        trajectory = rollout_episode(env, policy, sample_action, gamma)

        # Extract trajectory data
        states = trajectory["states"]
        actions = trajectory["actions"]
        rewards = trajectory["rewards"]
        angle_errors = trajectory["angle_errors"]

        # One action and reward per transition
        assert len(actions) == len(rewards)

        # State quantities include initial state
        assert len(states) == len(rewards) + 1
        assert len(angle_errors) == len(rewards) + 1

        # Episode contains exactly the allowed number of transitions
        assert len(rewards) == SIM_CONFIG.MAX_EPISODE_STEPS

        # Check trajectory fields
        assert set(trajectory) == {
            "states", "actions", "rewards", "angle_errors", "discounted_return",
        }

    finally:
        env.close()


# Test discounted episodic return
def test_rollout_discounted_return():
    # Initialise
    env = PlanarClawEnv(gui=False)
    policy = PolicyNetwork()
    gamma = 0.99

    try:
        # Sample trajectory
        trajectory = rollout_episode(env, policy, sample_action, gamma)

        # Compute expected discounted return
        expected_return = sum(
            (gamma ** t) * reward
            for t, reward in enumerate(trajectory["rewards"])
        )

        # Check returned value
        assert math.isclose(
            trajectory["discounted_return"],
            expected_return,
            rel_tol=1e-6,
        )

    finally:
        env.close()


# Test training trajectory lengths and final state
def test_sample_episode_length():
    # Initialise
    env = PlanarClawEnv(gui=False)
    policy = PolicyNetwork()

    try:
        # Sample trajectory
        trajectory = sample_episode(env, policy, sample_action)

        # Check trajectory fields
        assert set(trajectory) == {
            "states", "actions", "rewards", "log_probs", "final_state", "episode_length",
        }

        # Exactly one state per action, generated by that state (no extra final state)
        assert trajectory["episode_length"] == SIM_CONFIG.MAX_EPISODE_STEPS
        assert len(trajectory["states"]) == SIM_CONFIG.MAX_EPISODE_STEPS
        assert len(trajectory["actions"]) == SIM_CONFIG.MAX_EPISODE_STEPS
        assert len(trajectory["rewards"]) == SIM_CONFIG.MAX_EPISODE_STEPS
        assert len(trajectory["log_probs"]) == SIM_CONFIG.MAX_EPISODE_STEPS

        # Final state is the observation after the last transition
        np.testing.assert_array_equal(trajectory["final_state"], env.get_observation())

        # Stored probabilities score complete actions under the rollout policy
        with torch.no_grad():
            states = torch.tensor(np.array(trajectory["states"]), dtype=torch.float32)
            actions = torch.tensor(trajectory["actions"], dtype=torch.long)
            expected_log_probs = compute_action_log_probs(policy, states, actions)

        # Check every timestep's stored log-probability
        torch.testing.assert_close(torch.tensor(trajectory["log_probs"]), expected_log_probs)

    finally:
        env.close()


# Test that sample_episode returns plain trajectory data with no autograd graph
def test_sample_episode_has_no_autograd_graph():
    # Initialise
    env = PlanarClawEnv(gui=False)
    policy = PolicyNetwork()

    try:
        # Sample trajectory
        trajectory = sample_episode(env, policy, sample_action)

        # States are plain numpy observations, not torch tensors
        assert all(isinstance(state, np.ndarray) for state in trajectory["states"])

        # Actions are plain Python lists of ints, not torch tensors
        assert all(isinstance(action, list) for action in trajectory["actions"])
        assert all(isinstance(a, int) for action in trajectory["actions"] for a in action)

        # Rewards are plain Python floats, not torch tensors
        assert all(isinstance(reward, float) for reward in trajectory["rewards"])

        # Log-probabilities are plain Python floats
        assert all(isinstance(log_prob, float) for log_prob in trajectory["log_probs"])

        # Final state is a plain numpy observation
        assert isinstance(trajectory["final_state"], np.ndarray)

        # Nothing in the trajectory carries gradient tracking
        assert not any(
            isinstance(value, torch.Tensor) and value.requires_grad
            for values in trajectory.values()
            if isinstance(values, list)
            for value in values
        )

    finally:
        env.close()
